/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/63c6229f-a0a8-4dee-b135-16a11bd36ff2 
*/
#include "thingProperties.h"
#include "display_manager.h"
#include "data_manager.h"

void setup() {
  Serial.begin(9600);
  delay(1500); 
  
  // Initialize display and touch
  initDisplay();
  
  // Initialize data buffers
  initDataBuffers();
  
  // Initialize IoT Cloud
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  // Draw initial UI
  drawStaticElements();
}

void loop() {
  ArduinoCloud.update();
  handleTouch();
  
  if(needsRedraw()) {
    if(getCurrentScreen() == SCREEN_SETTINGS) {
      drawSettingsScreen();
    } else {
      drawGraph();
    }
    clearRedrawFlag();
  }
}

// IoT Cloud callback functions
void onTempChange() {
  addDataPoint((float)temp, humidity, pressure);
  Serial.print("Temperature updated: ");
  Serial.println((float)temp);
}

void onPressureChange() {
  updatePressureData(pressure);
  Serial.print("Pressure updated: ");
  Serial.println(pressure);
}

void onHumidityChange() {
  updateHumidityData(humidity);
  Serial.print("Humidity updated: ");
  Serial.println(humidity);
}

void onLightAlphaChange() {
  Serial.print("Light alpha updated: ");
  Serial.println(light_alpha);
}